name: VRX Midias Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

concurrency:
  group: vrx-midias-bot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          PYTHONUNBUFFERED: "1"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          YT_FEED_URL: ${{ secrets.YT_FEED_URL }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_GRAPH_VERSION: ${{ secrets.IG_GRAPH_VERSION }}
          MAX_ITEMS_PER_RUN: "3"
          DRY_RUN: "0"
          ALLOW_INITIAL_POST: "1"
          ALLOW_BATCH_POSTS: "1"
          BRAND_NAME: "Vorax eSports"
          YT_CHANNEL_URL: "https://youtube.com/@voraxsports"
          IG_PROFILE_URL: "https://www.instagram.com/voraxsportss/"
          # BRAND_ICON_URL: "https://SUA_URL_DA_IMAGEM.png"
          # BOT_AVATAR_URL: "https://SUA_URL_DA_IMAGEM.png"

        run: |
          python bot.py

      - name: Commit state if changed
        run: |
          git config user.name "vrx-bot"
          git config user.email "actions@users.noreply.github.com"
          git add state.json
          git diff --cached --quiet || git commit -m "chore: update state"
          git push
